#lang racket
(require "dom.rkt")

(define (dom-element-float-constraints dom)
  (apply append
         (for*/list ([elt (in-tree-values (dom-tree dom))])
           (match elt
             [`(<> ,name)
              '()]
             [`(,tag ,name)
              (define e (dom-get dom elt))
              (define pe `(,(dom-map dom) (parent ,(dom-get dom elt))))
              (define ve `(,(dom-map dom) (previous ,(dom-get dom elt))))
              (define b `(placement-box ,e))
              (define pb `(placement-box ,pe))
              (define vb `(placement-box ,ve))
              (define re `(rules ,(dom-get dom elt)))

              (list*
               ; CSS 2.1, § 9.5.1, item 1: The left outer edge of a left-floating box
               ; may not be to the left of the left edge of its containing block.
               ; An analogous rule holds for right-floating elements. 
               `(assert (=> (is-left (float ,b)) (>= (left-outer ,b) (box-left ,pb))))
               `(assert (=> (is-right (float ,b)) (<= (right-outer ,b) (box-right ,pb))))

               ; CSS 2.1, § 9.5.1, item 8: A floating box must be placed as high as possible. 
               ; NOTE: Simplified to be at its normal position, or the same y-position as another float
               `(assert (=> (not (is-none (float ,b)))
                            (or
                             (= (y ,b) (flow-box ,e))
                             ,@(for/list ([elt* (in-tree-values (dom-tree dom))] #:break (eq? elt elt*))
                                 (define b* `(placement-box ,(dom-get dom elt*)))
                                 `(and (not (is-none (float ,b*)))
                                       (= (top-outer ,b*) (top-outer ,b*)))))))

               ; CSS 2.1, § 9.5.1, item 9: A left-floating box must be put as far to the left
               ; as possible, a right-floating box as far to the right as possible. A higher
               ; position is preferred over one that is further to the left/right.  
               ; NOTE: simplified to being at the left/right or next to an existing box
               `(assert (=> (is-left (float ,b))
                            (or
                             (= (left-outer ,b)) (box-left ,pb))
                             ,@(for/list ([elt* (in-tree-values (dom-tree dom))] #:break (eq? elt elt*))
                                 (define b* `(placement-box ,(dom-get dom elt*)))
                                 `(and (is-left (float ,b*))
                                       (= (left-outer ,b) (right-outer ,b*))))))
               `(assert (=> (is-right (float ,b))
                            (or
                             (= (right-border ,b) (right-padding ,b*))
                             ,@(for/list ([elt* (in-tree-values (dom-tree dom))] #:break (eq? elt elt*))
                                 (define b* `(placement-box ,(dom-get dom elt*)))
                                 `(and (is-right (float ,b*))
                                       (= (right-outer ,b) (left-outer b*)))))))

               ; CSS 2.1, § 9.5.1, item 4: A floating box's outer top may not be higher
               ; than the top of its containing block. When the float occurs between
               ; two collapsing margins, the float is positioned as if it had an otherwise
               ; empty anonymous block parent taking part in the flow. The position of such
               ; a parent is defined by the rules in the section on margin collapsing. 
               `(assert (=> (or (is-left (float ,b)) (is-right (float ,b)))
                            (>= (top-outer ,b) (top-padding ,pb))))

               (apply append
                      ; The #:break ensures these are only preceding elements
                      (for/list ([elt* (in-tree-values (dom-tree dom))] #:break (eq? elt elt*))
                        (define b* `(placement-box ,(dom-get dom elt*)))

                        (list
                         ; CSS 2.1, § 9.5.1, item 2: If the current box is left-floating,
                         ; and there are any left-floating boxes generated by elements
                         ; earlier in the source document, then for each such earlier box,
                         ; either the left outer edge of the current box must be to the right
                         ; of the right outer edge of the earlier box, or its top must be lower
                         ; than the bottom of the earlier box.
                         ; Analogous rules hold for right-floating boxes. 
                         `(assert (=> (and (is-left (float ,b)) (is-left (float ,b*)))
                                      (or (>= (left-outer ,b) (right-outer ,b*))
                                          (>= (box-top ,b) (box-bottom ,b*)))))
                         `(assert (=> (and (is-right (float ,b)) (is-right (float ,b*)))
                                      (or (<= (right-outer ,b) (left-outer ,b*))
                                          (>= (box-top ,b) (box-bottom ,b*)))))

                         ; CSS 2.1, § 9.5.1, item 3: The right outer edge of a left-floating box
                         ; may not be to the right of the left outer edge of any right-floating box
                         ; that is next to it. Analogous rules hold for right-floating elements. 
                         `(assert (=> (and (is-left (float ,b)) (is-right (float ,b*))
                                           (or (> (+ (y ,b*) (h ,b*)) (y ,b) (y ,b*))
                                               (> (+ (y ,b) (h ,b)) (y ,b*) (y ,b))))
                                      (<= (right-outer ,b) (left-outer ,b*))))
                         `(assert (=> (and (is-right (float ,b)) (is-left (float ,b*))
                                           (or (> (+ (y ,b*) (h ,b*)) (y ,b) (y ,b*))
                                               (> (+ (y ,b) (h ,b)) (y ,b*) (y ,b))))
                                      (>= (left-outer ,b) (right-outer ,b*))))

                         ; CSS 2.1, § 9.5.1, item 5: The outer top of a floating box
                         ; may not be higher than the outer top of any block or floated box
                         ; generated by an element earlier in the source document. 
                         `(assert (=> (and (or (is-right (float ,b)) (is-left (float ,b)))
                                           (= (display ,e*) block))
                                      (>= (top-outer ,b) (top-outer ,b*))))

                         ; CSS 2.1 § 9.5.1, item 6: The outer top of an element's floating box
                         ; may not be higher than the top of any line-box containing a box
                         ; generated by an element earlier in the source document. 
                         `(assert (=> (and (or (is-right (float ,b)) (is-left (float ,b)))
                                           (= (display ,e*) inline))
                                      (>= (top-outer ,b) (- (y ,b*) (/ (gap ,b*) 2)))))

                         ; CSS 2.1, § 9.5.1, item 7: A left-floating box that has another
                         ; left-floating box to its left may not have its right outer edge
                         ; to the right of its containing block's right edge.
                         ; (Loosely: a left float may not stick out at the right edge,
                         ; unless it is already as far to the left as possible.)
                         ; An analogous rule holds for right-floating elements. 
                         ; TODO : is this equivalent to (at left edge /\ not over right edge)?
                         `(assert (=> (and (is-left (float ,b)) (is-left (float ,b*))
                                           (< (x ,b*) (x ,b))
                                           (or (> (+ (y ,b*) (h ,b*)) (y ,b) (y ,b*))
                                               (> (+ (y ,b) (h ,b)) (y ,b*) (y ,b))))
                                      (<= (right-outer ,b) (right-content ,pb))))
                         `(assert (=> (and (is-right (float ,b)) (is-right (float ,b*))
                                           (> (x ,b*) (x ,b))
                                           (or (> (+ (y ,b*) (h ,b*)) (y ,b) (y ,b*))
                                               (> (+ (y ,b) (h ,b)) (y ,b*) (y ,b))))
                                      (>= (left-outer ,b)
                                          (left-padding ,pb))))))))]))))
